class MainTemplate {
  static String generate({
    required String projectName,
    required String stateManagement,
    required bool includeFirebase,
    bool useRouter = false,
    bool useTheme = false,
  }) {
    final stateImports = <String>[];
    switch (stateManagement) {
      case 'riverpod':
        stateImports.add("import 'package:flutter_riverpod/flutter_riverpod.dart';");
        break;
      case 'provider':
        stateImports.add("import 'package:provider/provider.dart';");
        break;
      case 'bloc':
        stateImports.add("import 'package:flutter_bloc/flutter_bloc.dart';");
        break;
      default:
        break;
    }

    final imports = <String>[
      "import 'package:flutter/material.dart';",
      ...stateImports,
    ];

    if (useRouter) {
      imports.add("import 'app/router/app_router.dart';");
    }

    if (useTheme) {
      imports.add("import 'app/theme/app_theme.dart';");
    }

    if (includeFirebase) {
      imports.add("import 'package:firebase_core/firebase_core.dart';");
      imports.add("import 'firebase_options.dart';");
    }

    final importBlock = imports.join('\n');
    final title = _toTitleCase(projectName);

    final firebaseInit = includeFirebase
        ? '''
  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
'''
        : '';

    String runAppInvocation;
    switch (stateManagement) {
      case 'riverpod':
        runAppInvocation = 'runApp(const ProviderScope(child: MyApp()));';
        break;
      case 'provider':
        runAppInvocation = '''runApp(
    MultiProvider(
      providers: [
        // TODO: add providers
      ],
      child: const MyApp(),
    ),
  );''';
        break;
      case 'bloc':
        runAppInvocation = '''runApp(
    MultiBlocProvider(
      providers: [
        // TODO: add BlocProviders
      ],
      child: const MyApp(),
    ),
  );''';
        break;
      default:
        runAppInvocation = 'runApp(const MyApp());';
    }

    final themeConfig = useTheme
        ? '''
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,'''
        : '''
      theme: ThemeData(
        primarySwatch: Colors.blue,
        useMaterial3: true,
      ),
      darkTheme: ThemeData.dark(),
      themeMode: ThemeMode.system,''';

    if (useRouter) {
      return '''
$importBlock

// $title — generated by superapp_cli

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
$firebaseInit
  // TODO: Initialize dependency injection if used

  $runAppInvocation
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: '$title',
      debugShowCheckedModeBanner: false,$themeConfig
      routerConfig: appRouter,
    );
  }
}
''';
    } else {
      return '''
$importBlock

// $title — generated by superapp_cli

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
$firebaseInit
  // TODO: Initialize dependency injection if used

  $runAppInvocation
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '$title',
      debugShowCheckedModeBanner: false,$themeConfig
      home: const Scaffold(
        body: Center(
          child: Text('Welcome to $title'),
        ),
      ),
    );
  }
}
''';
    }
  }

  static String _toTitleCase(String input) {
    final parts = input.split(RegExp(r'[_\s]+'));
    final capitalized = parts.map((p) {
      if (p.isEmpty) return '';
      return p[0].toUpperCase() + p.substring(1);
    }).join(' ');
    return capitalized;
  }
}